# Basic
title: Horex
subtitle: HorexC - blog
description: Horex 的blog 写了一些tips ...

url: "http://HorexC.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Horex
    github: Horex
    twitter: Horex
    mail: horex@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
